apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgrasi
  labels:
    name: tgrasi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tgrasi
  template:
    metadata:
      name: tgrasi
      labels:
        app: tgrasi
    spec:
      containers:
      - name: tgrasi
        image: ghcr.io/alisajid/k8s_workshop:1.2.0
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: github-api-creds
                key: CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: github-api-creds
                key: CLIENT_SECRET
          - name: ENV
            value: "prod"
          - name: DEBUG
            value: "False"
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "5000"
