---
apiVersion: v1
kind: Service
metadata:
  name: tgrasi
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: tgrasi_mapping
      prefix: /tgrasi
      service: tgrasi:5000

spec:
  ports:
  - name: tgrasi
    port: 5000
    targetPort: 5000
  selector:
    app: tgrasi