apiVersion: v1
kind: Service
metadata:
  name: tgrlb
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"
  labels:
    name: tgrlb
spec:
  selector:
    app: tgrasi
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
