apiVersion: v1
kind: ReplicationController
metadata:
  name: app
spec:
  replicas: 3
  selector:
    app: app
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: tgrapp
          image: ghcr.io/alisajid/k8s_workshop:1.0.3
          ports:
            - containerPort: 5000
